[debug] [2025-05-23T02:24:18.434Z] ----------------------------------------------------------------------
[debug] [2025-05-23T02:24:18.450Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\PRATIK\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2025-05-23T02:24:18.450Z] CLI Version:   14.2.0
[debug] [2025-05-23T02:24:18.451Z] Platform:      win32
[debug] [2025-05-23T02:24:18.451Z] Node Version:  v20.11.0
[debug] [2025-05-23T02:24:18.451Z] Time:          Fri May 23 2025 07:54:18 GMT+0530 (India Standard Time)
[debug] [2025-05-23T02:24:18.452Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-05-23T02:24:18.458Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] Already logged in as pmore3170@gmail.com
[debug] [2025-05-23T02:24:24.537Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2025-05-23T02:24:24.538Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2025-05-23T02:24:25.006Z] Error: Timed out.
    at Timeout.<anonymous> (C:\Users\PRATIK\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:269:49)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
[error] 
[error] Error: An unexpected error has occurred.
